"""
mcx_instruments.py
The MCX commodity futures universe (full-size + mini/micro), with REAL
front-month Upstox instrument_keys pulled from the Upstox MCX instrument
master.

Generated by tools/refresh_mcx.py — do not hand-edit. MCX futures keys
EXPIRE, so regenerate this each expiry (or monthly) by running
`python tools/refresh_mcx.py`. config prefers this module when present and
falls back to its inline list otherwise.

`reference_price` seeds the SIMULATED feed only; real backtest and live
trading use actual market data, so it need not be exact.
"""
from config import Instrument, Segment

MCX_INSTRUMENTS = [
    Instrument("GOLD", Segment.MCX, "MCX_FO|483079", 1, 1.0, 142419.0, 100, expiry="2026-10-05"),   # GRMS, expires 05-Oct-2026
    Instrument("CRUDEOIL", Segment.MCX, "MCX_FO|560977", 100, 1.0, 7580.0, 100, expiry="2026-08-19"),   # BBL, expires 19-Aug-2026
    Instrument("NATURALGAS", Segment.MCX, "MCX_FO|561496", 1250, 0.1, 279.7, 1250, expiry="2026-08-26"),   # mmBtu, expires 26-Aug-2026
    Instrument("SILVER", Segment.MCX, "MCX_FO|471725", 30, 1.0, 223320.0, 30, expiry="2026-09-04"),   # KGS, expires 04-Sep-2026
    Instrument("GOLDM", Segment.MCX, "MCX_FO|563946", 100, 1.0, 142419.0, 10, expiry="2026-09-04"),   # GRMS, expires 04-Sep-2026
    Instrument("CRUDEOILM", Segment.MCX, "MCX_FO|560978", 10, 1.0, 7580.0, 10, expiry="2026-08-19"),   # BBL, expires 19-Aug-2026
    Instrument("NATGASMINI", Segment.MCX, "MCX_FO|561497", 250, 0.1, 279.7, 250, expiry="2026-08-26"),   # mmBtu, expires 26-Aug-2026
    Instrument("SILVERM", Segment.MCX, "MCX_FO|471726", 5, 1.0, 223320.0, 5, expiry="2026-08-31"),   # KGS, expires 31-Aug-2026
    Instrument("SILVERMIC", Segment.MCX, "MCX_FO|488788", 1, 1.0, 223320.0, 1, expiry="2026-08-31"),   # KGS, expires 31-Aug-2026
]
