"""
mcx_instruments.py
The MCX commodity futures universe (full-size + mini/micro), with REAL
front-month Upstox instrument_keys pulled from the Upstox MCX instrument
master.

Generated by tools/refresh_mcx.py — do not hand-edit. MCX futures keys
EXPIRE, so regenerate this each expiry (or monthly) by running
`python tools/refresh_mcx.py`. config prefers this module when present and
falls back to its inline list otherwise.

`reference_price` seeds the SIMULATED feed only; real backtest and live
trading use actual market data, so it need not be exact.
"""
from config import Instrument, Segment

MCX_INSTRUMENTS = [
    Instrument("GOLD", Segment.MCX, "MCX_FO|466583", 1, 1.0, 142419.0, 100),   # GRMS, expiry 05-Aug-2026
    Instrument("CRUDEOIL", Segment.MCX, "MCX_FO|520702", 100, 1.0, 7580.0, 100),   # BBL, expiry 20-Jul-2026
    Instrument("NATURALGAS", Segment.MCX, "MCX_FO|538685", 1250, 0.1, 279.7, 1250),   # mmBtu, expiry 28-Jul-2026
    Instrument("SILVER", Segment.MCX, "MCX_FO|471725", 30, 1.0, 223320.0, 30),   # KGS, expiry 04-Sep-2026
    Instrument("GOLDM", Segment.MCX, "MCX_FO|555922", 100, 1.0, 142419.0, 10),   # GRMS, expiry 05-Aug-2026
    Instrument("CRUDEOILM", Segment.MCX, "MCX_FO|520703", 10, 1.0, 7580.0, 10),   # BBL, expiry 20-Jul-2026
    Instrument("NATGASMINI", Segment.MCX, "MCX_FO|538686", 250, 0.1, 279.7, 250),   # mmBtu, expiry 28-Jul-2026
    Instrument("SILVERM", Segment.MCX, "MCX_FO|471726", 5, 1.0, 223320.0, 5),   # KGS, expiry 31-Aug-2026
    Instrument("SILVERMIC", Segment.MCX, "MCX_FO|488788", 1, 1.0, 223320.0, 1),   # KGS, expiry 31-Aug-2026
]
