"""
tools/refresh_nifty100.py
Regenerate ../nifty100_instruments.py from the live Upstox NSE instrument master.

Run when Nifty 100 index membership changes (or a constituent re-symbols, as
LTIMindtree -> LTM and Tata Motors -> TMPV/TMCV did):

    python tools/refresh_nifty100.py

It downloads the Upstox NSE master, matches the constituent trading symbols
below, and writes real ISIN-based instrument_keys. Any symbol not found in the
master is reported and skipped, so a stale name can never break config import.
"""
from __future__ import annotations

import gzip
import json
import os
import sys
import urllib.request

# Nifty 100 = Nifty 50 + Nifty Next 50. Trading symbols as they appear in the
# Upstox NSE master (note recent re-symbols: LTIMindtree=LTM, Tata Motors split
# into TMPV/TMCV, Solar Industries=SOLARINDS).
NIFTY100 = [
    # --- Nifty 50 ---
    "ADANIENT", "ADANIPORTS", "APOLLOHOSP", "ASIANPAINT", "AXISBANK",
    "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV", "BEL", "BHARTIARTL",
    "BPCL", "BRITANNIA", "CIPLA", "COALINDIA", "DRREDDY", "EICHERMOT",
    "GRASIM", "HCLTECH", "HDFCBANK", "HDFCLIFE", "HEROMOTOCO", "HINDALCO",
    "HINDUNILVR", "ICICIBANK", "INDUSINDBK", "INFY", "ITC", "JSWSTEEL",
    "KOTAKBANK", "LT", "LTM", "M&M", "MARUTI", "NESTLEIND", "NTPC",
    "ONGC", "POWERGRID", "RELIANCE", "SBILIFE", "SBIN", "SHRIRAMFIN",
    "SUNPHARMA", "TATACONSUM", "TMPV", "TMCV", "TATASTEEL", "TCS", "TECHM",
    "TITAN", "TRENT", "ULTRACEMCO", "WIPRO", "JIOFIN", "ETERNAL",
    # --- Nifty Next 50 (and recent large caps) ---
    "ABB", "ADANIENSOL", "ADANIGREEN", "ADANIPOWER", "AMBUJACEM", "DMART",
    "BAJAJHLDNG", "BANKBARODA", "BERGEPAINT", "BOSCHLTD", "CANBK",
    "CGPOWER", "CHOLAFIN", "COLPAL", "DABUR", "DIVISLAB", "DLF", "GAIL",
    "GODREJCP", "HAVELLS", "HDFCAMC", "ICICIGI", "ICICIPRULI", "INDHOTEL",
    "INDIGO", "IOC", "IRFC", "JINDALSTEL", "LODHA", "LICI", "MOTHERSON",
    "NAUKRI", "PIDILITIND", "PFC", "PNB", "RECLTD", "SIEMENS", "SRF",
    "TATAPOWER", "TORNTPHARM", "TVSMOTOR", "UNITDSPR", "VBL", "VEDL",
    "ZYDUSLIFE", "MANKIND", "NHPC", "GODREJPROP", "HAL", "IRCTC",
    "MAXHEALTH", "MUTHOOTFIN", "POLYCAB", "SOLARINDS", "OFSS",
    "PGHH", "SWIGGY", "IDEA", "MAZDOCK", "BHARTIHEXA",
]

URL = "https://assets.upstox.com/market-quote/instruments/exchange/NSE.json.gz"
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "nifty100_instruments.py")


def main() -> int:
    print(f"Downloading {URL} ...", file=sys.stderr)
    rows = json.loads(gzip.decompress(urllib.request.urlopen(URL, timeout=60).read()))
    eq = {x["trading_symbol"]: x for x in rows
          if x.get("segment") == "NSE_EQ" and x.get("instrument_type") == "EQ"
          and x.get("security_type") == "NORMAL"}

    found, missing, seen = [], [], set()
    for sym in NIFTY100:
        if sym in seen:
            continue
        seen.add(sym)
        (found if sym in eq else missing).append(eq.get(sym, sym))

    found.sort(key=lambda x: x["trading_symbol"])
    print(f"matched {len(found)} / {len(seen)}  missing={missing}", file=sys.stderr)

    body = "\n".join(
        f'    Instrument("{x["trading_symbol"]}", Segment.EQUITY, '
        f'"{x["instrument_key"]}", 1, 0.05, 1000.0),' for x in found)
    header = ('"""\n'
              "nifty100_instruments.py\n"
              "The Nifty 100 equity universe (Nifty 50 + Nifty Next 50), with "
              "REAL Upstox\ninstrument_keys (ISIN-based) pulled from the Upstox "
              "NSE instrument master.\n\n"
              "Generated by tools/refresh_nifty100.py — do not hand-edit. "
              "Instrument keys are\nISIN-based and stable across sessions (they "
              "do not expire like MCX futures),\nso this list only needs "
              "regenerating when index membership changes.\n\n"
              "`reference_price` is a nominal seed for the SIMULATED feed only; "
              "real backtest\nand live trading use actual market data, so it "
              "need not be exact.\n"
              '"""\n'
              "from config import Instrument, Segment\n\n"
              "NIFTY100_INSTRUMENTS = [\n")
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(header + body + "\n]\n")
    print(f"wrote {len(found)} instruments to {OUT}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
