"""
tools/refresh_us.py
Regenerate us_instruments.py from Alpaca's live asset master.

    python tools/refresh_us.py                 # keep the current universe, drop dead tickers
    python tools/refresh_us.py --top 200       # the 200 most-traded names instead
    python tools/refresh_us.py --add PLTR HOOD # append specific symbols

YOU DO NOT NEED TO RUN THIS. us_instruments.py is checked in and works out of
the box; this exists for when a name is renamed, acquired or delisted, or when
you want a different universe. It mirrors tools/refresh_mcx.py in spirit, with
one happy difference: a US instrument_key is just its ticker, and tickers do not
expire the way MCX futures keys do — so this list rots slowly, not monthly.

Needs ALPACA_API_KEY / ALPACA_API_SECRET. Without them it exits without
touching anything, because writing a truncated universe would be worse than
leaving the existing one alone.
"""
from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv  # noqa: E402

load_dotenv()

import alpaca_data  # noqa: E402

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "us_instruments.py")

HEADER = '''"""
us_instruments.py
The US equity universe traded through Alpaca — GENERATED by tools/refresh_us.py.

A US `instrument_key` is just the ticker: there is no ISIN-style lookup, and
nothing expires the way MCX futures keys do, so this list only goes stale when
a company is renamed, acquired or delisted.

`reference_price` seeds the SIMULATED feed only; real backtests and live
trading use actual market data, so it does not need to be accurate. USD.
"""
from config import Instrument, Segment

US_INSTRUMENTS = [
'''


def current_symbols() -> list[str]:
    try:
        from us_instruments import US_INSTRUMENTS
        return [i.symbol for i in US_INSTRUMENTS]
    except Exception:
        return []


def current_refs() -> dict[str, float]:
    """Keep the seed prices we already have so a refresh doesn't reset them."""
    try:
        from us_instruments import US_INSTRUMENTS
        return {i.symbol: float(i.reference_price) for i in US_INSTRUMENTS}
    except Exception:
        return {}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--top", type=int, default=0,
                    help="take the first N tradable symbols alphabetically "
                         "instead of keeping the current list")
    ap.add_argument("--add", nargs="*", default=[],
                    help="extra symbols to append")
    args = ap.parse_args()

    if not alpaca_data.is_configured():
        print("ALPACA_API_KEY / ALPACA_API_SECRET are not set — nothing written.\n"
              "us_instruments.py is left exactly as it is, which is safer than\n"
              "replacing it with a list built from no data.")
        return 1

    tradable = set(alpaca_data.list_tradable_symbols())
    if not tradable:
        print("Alpaca returned no assets — nothing written.")
        return 1
    print(f"Alpaca reports {len(tradable):,} active tradable US equities.")

    if args.top:
        wanted = sorted(tradable)[:args.top]
    else:
        keep = [s for s in current_symbols() if s in tradable]
        dropped = [s for s in current_symbols() if s not in tradable]
        if dropped:
            print(f"Dropping {len(dropped)} symbol(s) Alpaca no longer lists: "
                  f"{', '.join(dropped)}")
        wanted = keep
    for s in args.add:
        s = s.upper()
        if s not in wanted and s in tradable:
            wanted.append(s)
        elif s not in tradable:
            print(f"  !! {s} is not tradable on Alpaca — skipped")

    refs = current_refs()
    lines = [f'    Instrument("{s}", Segment.US_EQUITY, "{s}", 1, 0.01, '
             f'{refs.get(s, 120.0)}),' for s in wanted]
    with open(OUT, "w", encoding="utf-8", newline="") as fh:
        fh.write(HEADER + "\n".join(lines) + "\n]\n")
    print(f"Wrote {OUT} with {len(wanted)} instruments.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
